URL = "http://linuxchat.herokuapp.com/"

#URL = "http://localhost:5000/"
postURL = URL + "api/chat/"
getURL = URL + "api/chat/"
usersURL = URL + "api/users/"
loginURL = URL + "api/users/login"
addfriendURL = URL + "api/users/addfriend/"
updateURL = URL + "api/users/update/"
removeURL = URL + "api/users/removefriend/"
loguotURL = URL + "api/users/logout/"
registerURL = URL + "api/users/register"